"""create_initial_schema

Revision ID: 56bc0451d50b
Revises: 
Create Date: 2026-09-23 18:13:15.946696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bc0451d50b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('variable', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_data_range', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('sensor_specs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'decommissioned', name='station_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index('idx_stations_lat_lon', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_station_code'), ['station_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'data_quality_officer', 'forecaster', 'field_technician', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('maintenance_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_probability_30d', sa.Float(), nullable=False),
    sa.Column('top_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_predictions_station_id'), ['station_id'], unique=False)

    op.create_table('raw_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('ingest_source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'timestamp', name='uq_station_timestamp')
    )
    with op.batch_alter_table('raw_readings', schema=None) as batch_op:
        batch_op.create_index('idx_raw_readings_station_time', ['station_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_readings_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_readings_timestamp'), ['timestamp'], unique=False)

    op.create_table('qc_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reading_id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('variable', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.Enum('valid', 'suspect', 'anomalous', name='qc_verdict'), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('fault_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['raw_readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qc_results', schema=None) as batch_op:
        batch_op.create_index('idx_qc_results_station_created', ['station_id', 'created_at'], unique=False)
        batch_op.create_index('idx_qc_results_verdict', ['verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_qc_results_reading_id'), ['reading_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qc_results_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qc_results_verdict'), ['verdict'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('qc_result_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alert_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel_sent', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['qc_result_id'], ['qc_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_qc_result_id'), ['qc_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_station_id'), ['station_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('qc_result_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('label', sa.Enum('confirmed_fault', 'false_alarm', 'unsure', name='feedback_label'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qc_result_id'], ['qc_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_qc_result_id'), ['qc_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_qc_result_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_station_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_qc_result_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('qc_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_results_verdict'))
        batch_op.drop_index(batch_op.f('ix_qc_results_station_id'))
        batch_op.drop_index(batch_op.f('ix_qc_results_reading_id'))
        batch_op.drop_index('idx_qc_results_verdict')
        batch_op.drop_index('idx_qc_results_station_created')

    op.drop_table('qc_results')
    with op.batch_alter_table('raw_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_raw_readings_station_id'))
        batch_op.drop_index('idx_raw_readings_station_time')

    op.drop_table('raw_readings')
    with op.batch_alter_table('maintenance_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_predictions_station_id'))

    op.drop_table('maintenance_predictions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_station_code'))
        batch_op.drop_index('idx_stations_lat_lon')

    op.drop_table('stations')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
